### ISSUE TITLE
Build failure on `Fedora-22` and `openSUSE-13.2`

### ISSUE THREAD

**Issue by dilawar** [aviralg/moogli#9]
```
[   89s] In file included from build/temp.linux-x86_64-2.7/sip_mooglicmodule.cpp:7:0:
[   89s] build/temp.linux-x86_64-2.7/sipAPI_moogli.h:13:21: fatal error: QMetaType: No such file or directory
```

I already have following installed (from spec file)

```
BuildRequires: cmake
BuildRequires: gcc-c++
BuildRequires: PyQt4-devel
BuildRequires: PyQt
BuildRequires: OpenSceneGraph-devel
BuildRequires: OpenSceneGraph-qt-devel
BuildRequires: python-setuptools
BuildRequires: qt-devel
BuildRequires: qt
BuildRequires: sip-devel
```

Do I need something more to build moogli on Fedora/openSUSE. I build previous version of MOOGLI using the same spec file.

**Comment by dilawar** [comment]
More detailed log can be found [here](https://build.opensuse.org/package/show/home:moose/moogli)

**Comment by dilawar** [comment]
It builds fine on Ubuntu (except 12.04 or lower).

**Comment by dilawar** [comment]
Needed to extend the list of include paths: Fixed by commit https://github.com/BhallaLab/moogli/commit/217b3fbca74d1dc9277e75b9282d606c7cc3c422
